basePath: /
definitions:
  go-app-marketplace_pkg_reqresp.ErrorInfo:
    properties:
      code:
        type: integer
      details:
        type: string
    type: object
  go-app-marketplace_pkg_reqresp.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  go-app-marketplace_pkg_reqresp.RegisterUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  go-app-marketplace_pkg_reqresp.StandardResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/go-app-marketplace_pkg_reqresp.ErrorInfo'
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the online marketplace.
  title: Online Marketplace
  version: "0.1"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates user and returns JWT token
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/go-app-marketplace_pkg_reqresp.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
      summary: Login user
      tags:
      - users
  /refresh:
    post:
      description: Refreshes JWT access token using refresh_token cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
      summary: Refresh access token
      tags:
      - users
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user with username, email, and password
      parameters:
      - description: User registration input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/go-app-marketplace_pkg_reqresp.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
      summary: Register new user
      tags:
      - users
  /verify:
    get:
      description: Verifies the JWT token in Authorization header
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/go-app-marketplace_pkg_reqresp.StandardResponse'
      security:
      - BearerAuth: []
      summary: Verify JWT access token
      tags:
      - users
swagger: "2.0"
